name: Gradle Build Test

# attempt to build the code whenever code is pushed to the repo
on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
